[package]
name = "perspectivedb-std"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
perspectivedb-core = { version = "0.1.0", path = "../core" }
thiserror = "2.0.16"
unicode-normalization = "0.1.24"
